// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.0--rc2
// source: workerpb/worker.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GrpcWorkerClient is the client API for GrpcWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcWorkerClient interface {
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteReply, error)
}

type grpcWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcWorkerClient(cc grpc.ClientConnInterface) GrpcWorkerClient {
	return &grpcWorkerClient{cc}
}

func (c *grpcWorkerClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteReply, error) {
	out := new(ExecuteReply)
	err := c.cc.Invoke(ctx, "/proto.GrpcWorker/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcWorkerServer is the server API for GrpcWorker service.
// All implementations must embed UnimplementedGrpcWorkerServer
// for forward compatibility
type GrpcWorkerServer interface {
	Execute(context.Context, *ExecuteRequest) (*ExecuteReply, error)
	mustEmbedUnimplementedGrpcWorkerServer()
}

// UnimplementedGrpcWorkerServer must be embedded to have forward compatible implementations.
type UnimplementedGrpcWorkerServer struct {
}

func (UnimplementedGrpcWorkerServer) Execute(context.Context, *ExecuteRequest) (*ExecuteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedGrpcWorkerServer) mustEmbedUnimplementedGrpcWorkerServer() {}

// UnsafeGrpcWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcWorkerServer will
// result in compilation errors.
type UnsafeGrpcWorkerServer interface {
	mustEmbedUnimplementedGrpcWorkerServer()
}

func RegisterGrpcWorkerServer(s grpc.ServiceRegistrar, srv GrpcWorkerServer) {
	s.RegisterService(&GrpcWorker_ServiceDesc, srv)
}

func _GrpcWorker_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcWorkerServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GrpcWorker/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcWorkerServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GrpcWorker_ServiceDesc is the grpc.ServiceDesc for GrpcWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GrpcWorker",
	HandlerType: (*GrpcWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _GrpcWorker_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workerpb/worker.proto",
}
