// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.0--rc2
// source: workerpb/worker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 交付任务包括：
// 幂等信息（JobId, TriggerTime)
// 执行器（ExecutorType, ExecutorInfo）
type ExecuteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId        uint32 `protobuf:"varint,1,opt,name=JobId,proto3" json:"JobId,omitempty"`
	TriggerTime  uint32 `protobuf:"varint,2,opt,name=TriggerTime,proto3" json:"TriggerTime,omitempty"`
	ExecutorType string `protobuf:"bytes,3,opt,name=ExecutorType,proto3" json:"ExecutorType,omitempty"`
	ExecutorInfo string `protobuf:"bytes,4,opt,name=ExecutorInfo,proto3" json:"ExecutorInfo,omitempty"`
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workerpb_worker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workerpb_worker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_workerpb_worker_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetJobId() uint32 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *ExecuteRequest) GetTriggerTime() uint32 {
	if x != nil {
		return x.TriggerTime
	}
	return 0
}

func (x *ExecuteRequest) GetExecutorType() string {
	if x != nil {
		return x.ExecutorType
	}
	return ""
}

func (x *ExecuteRequest) GetExecutorInfo() string {
	if x != nil {
		return x.ExecutorInfo
	}
	return ""
}

type ExecuteReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok int32 `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
}

func (x *ExecuteReply) Reset() {
	*x = ExecuteReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workerpb_worker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteReply) ProtoMessage() {}

func (x *ExecuteReply) ProtoReflect() protoreflect.Message {
	mi := &file_workerpb_worker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteReply.ProtoReflect.Descriptor instead.
func (*ExecuteReply) Descriptor() ([]byte, []int) {
	return file_workerpb_worker_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteReply) GetOk() int32 {
	if x != nil {
		return x.Ok
	}
	return 0
}

var File_workerpb_worker_proto protoreflect.FileDescriptor

var file_workerpb_worker_proto_rawDesc = []byte{
	0x0a, 0x15, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x70, 0x62, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x90,
	0x01, 0x0a, 0x0e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x54, 0x72, 0x69, 0x67, 0x67,
	0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x54, 0x72,
	0x69, 0x67, 0x67, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a,
	0x0c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0x1e, 0x0a, 0x0c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x4f,
	0x6b, 0x32, 0x45, 0x0a, 0x0a, 0x47, 0x72, 0x70, 0x63, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12,
	0x37, 0x0a, 0x07, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_workerpb_worker_proto_rawDescOnce sync.Once
	file_workerpb_worker_proto_rawDescData = file_workerpb_worker_proto_rawDesc
)

func file_workerpb_worker_proto_rawDescGZIP() []byte {
	file_workerpb_worker_proto_rawDescOnce.Do(func() {
		file_workerpb_worker_proto_rawDescData = protoimpl.X.CompressGZIP(file_workerpb_worker_proto_rawDescData)
	})
	return file_workerpb_worker_proto_rawDescData
}

var file_workerpb_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_workerpb_worker_proto_goTypes = []interface{}{
	(*ExecuteRequest)(nil), // 0: proto.ExecuteRequest
	(*ExecuteReply)(nil),   // 1: proto.ExecuteReply
}
var file_workerpb_worker_proto_depIdxs = []int32{
	0, // 0: proto.GrpcWorker.Execute:input_type -> proto.ExecuteRequest
	1, // 1: proto.GrpcWorker.Execute:output_type -> proto.ExecuteReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workerpb_worker_proto_init() }
func file_workerpb_worker_proto_init() {
	if File_workerpb_worker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_workerpb_worker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workerpb_worker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_workerpb_worker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workerpb_worker_proto_goTypes,
		DependencyIndexes: file_workerpb_worker_proto_depIdxs,
		MessageInfos:      file_workerpb_worker_proto_msgTypes,
	}.Build()
	File_workerpb_worker_proto = out.File
	file_workerpb_worker_proto_rawDesc = nil
	file_workerpb_worker_proto_goTypes = nil
	file_workerpb_worker_proto_depIdxs = nil
}
